#pyproject.toml
[build-system]
# Minimum requirements for the build system to execute.
requires = ['setuptools>=45.0,<72.0', 'wheel', 'cython>=0.29,<3.0', 'numpy>=1.25,<2.0.0',
            "mpi4py==3.1.5"]
