rm -f core*
rm -f opt.out
rm -f test.*
rm -f *tec_boundary*
rm -f tacs_iter*
rm -f nan*
rm -f *.f5
rm -f *.vtk
rm -f funtofem_adjoint*
rm -f *.flow
rm -f *.grid_info
rm -f *geom_cons_law.dat
rm -f *subhist.dat
rm -f steady/Flow/core*
rm -f stead/Flow/*.vtk
rm -f steady/Flow/*tec_boundary*
rm -f steady/Flow/tets.grid_info
rm -f steady/Flow/tets.flow
rm -f steady/Flow/tets_volume*
rm -f steady/Flow/tets_hist*
rm -f steady/Flow/tets.forces
rm -f steady/Flow/tets.forces_imaginary
rm -f steady/Adjoint/*
#cp ../restart_adjoint/steady/Flow/tets.flow steady/Flow/.
