mpi:
  - mpich
  - openmpi

scalar:
  - real
  - complex

python:
  - 3.9
  - 3.10
  - 3.11
  - 3.12

target_platform:
  - osx-64 # [osx]
  #- osx-arm64 # [osx]
  - linux-64 # [linux64]
  #- linux-aarch64 # [linux64]
  #- linux-ppc64le # [linux64]