{% set name = "funtofem" %}

{% set version = environ.get('GIT_DESCRIBE_TAG', '') %}
{% if version.startswith('v') %}
{% set version = version[1:] %}
{% endif %}
# {% set version = 0.2 %}

{% set build = 0 %}

{% set mpi = mpi or 'openmpi' %}
{% if scalar == "real" %}
{% set build = build + 100 %}
{% endif %}

# to test the build run the following command from the F2F root folder
# conda build -c conda-forge -c smdogroup/label/complex -c smdogroup conda;
# how to install conda for testing
# conda install -c smdogroup -c conda-forge -c sean-engelstad funtofem

package:
  name: "funtofem"
  version: "{{ version }}"

source:
  git_url: https://github.com/smdogroup/funtofem.git

build:
  number: {{ build }}
  skip: true  # [py<=38]
  string: py{{ CONDA_PY }}_{{ scalar }}_h{{ PKG_HASH }}_{{ build }}
  track_features:
    - funtofem_complex  # [scalar == "complex"]

requirements:
  build:
    - {{compiler('cxx')}}
    - make
    - python {{ python }}                    # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy   >=1.25 # [build_platform != target_platform]
    - openmpi >=4.1.4 # [mpi == "openmpi" and build_platform != target_platform]
    - mpich  # [mpi == "mpich" and build_platform != target_platform]
    - openmpi-mpicxx  # [mpi == "openmpi" and build_platform != target_platform]
    - mpich-mpicxx  # [mpi == "mpich" and build_platform != target_platform]
    - mpi4py >=3.1.5,<4.0.0 # [build_platform != target_platform]
    - cython >=0.29,<3.0 # [build_platform != target_platform]
    - setuptools # [build_platform != target_platform]
    - tacs >=3.4.0 # [build_platform != target_platform]

  host:
    - python {{ python }}
    - pip
    - numpy   >=1.25
    - openmpi >=4.1.4 # [mpi == "openmpi"]
    - mpich  # [mpi == "mpich"]
    - libopenblas
    - lapack
    - mpi4py >=3.1.5,<4.0.0
    - cython >=0.29,<3.0
    - tacs >=3.4.0

  run:
    - python
    - {{ pin_compatible("numpy") }}
    - scipy
    - openmpi >=4.1.4 # [mpi == "openmpi"]
    - mpich  # [mpi == "mpich"]
    - libopenblas
    - lapack
    - mpi4py >=3.1.5,<4.0.0
    - tacs >=3.4.0

test:
  requires:
    - testflo

  source_files:
    - tests

  imports:
    - tacs
    - tacs.pytacs
    - funtofem
    - funtofem.driver
    - funtofem.model
    - funtofem.interface
    - funtofem.optimization
    - funtofem.TransferScheme

  commands:
    - |
    - testflo --pre_announce --timeout 120 tests/unit_tests # [linux64]

about:
  home: https://github.com/smdogroup/funtofem
  license: Apache
  license_family: APACHE
  summary: Aeroelastic analysis package with adjoint-based gradient optimization
  doc_url: https://smdogroup.github.io/funtofem/
