rm -f core*
rm -f *.out
rm -f test.*
rm -f *tec_boundary*
rm -f tacs_iter*
rm -f nan*
rm -f *.f5
rm -f *.vtk
rm -f subsonic_wedge*
rm -f *.flow
rm -f *.grid_info
rm -f *geom_cons_law.dat
rm -f *subhist.dat
rm -f steady/Flow/*.f5
rm -f steady/Flow/core*
rm -f stead/Flow/*.vtk
rm -f steady/Flow/*tec_boundary*
rm -f steady/Flow/*.grid_info
rm -f steady/Flow/*.flow
rm -f steady/Flow/*_volume*
rm -f steady/Flow/*_hist*
rm -f steady/Flow/*.forces
rm -f steady/Flow/*.forces_imaginary
rm -f steady/Flow/fort*
rm -f steady/Adjoint/*
rm -f *.npy
rm -rf optimization_*
echo 0 > COUNT
#cp ../restart_adjoint/steady/Flow/tets.flow steady/Flow/.
