name: Unit tests for updated formulation

on:
  # Triggers the workflow on push or pull request events but only for the master branch.
  # Remove push when finally merging.
  push:
    branches: [ updated-formulation ]
  pull_request:
    branches: [ updated-formulation ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  # This job is called test_docs.
  unit_tests:
    # Recommended if you intend to make multiple deployments in quick succession
    concurrency: ci-${{ github.ref }}
    # Run on Ubuntu
    runs-on: ubuntu-latest
    # Necessary to prevent mpi tests failing due to lack of slots
    env:
      OMPI_MCA_btl: self,tcp
      OMPI_MCA_rmaps_base_oversubscribe: 1
    # Ensures conda environment is initialized for all steps
    defaults:
      run:
        shell: bash -l {0}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          # real versions
          - NAME: Real
            OPTIONAL: 'default'
            INTERFACE: 'interface'

          # complex versions
          #- NAME: Complex
          #  OPTIONAL: 'complex'
          #  INTERFACE: 'complex_interface'
          #  PUBLISH_DOCS: false

    name: FUNtoFEM ${{ matrix.NAME }} Build/Test

    steps:
      - name: Display run details
        run: |
          echo "=============================================================";
          echo "Run #${GITHUB_RUN_NUMBER}";
          echo "Run ID: ${GITHUB_RUN_ID}";
          echo "Testing: ${GITHUB_REPOSITORY}";
          echo "Triggered by: ${GITHUB_EVENT_NAME}";
          echo "Initiated by: ${GITHUB_ACTOR}";
          echo "=============================================================";

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - uses: actions/checkout@v2

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9

      - name: Install TACS
        run: |
          git clone https://github.com/smdogroup/tacs.git /home/runner/work/tacs;
          export TACS_DIR=/home/runner/work/tacs;
          conda install -c conda-forge sysroot_linux-64=2.17 -q -y;
          conda install -c conda-forge openmpi openmpi-mpicxx -q -y;
          conda install -c anaconda openblas -q -y;
          conda install -c conda-forge lapack -q -y;
          conda install -c conda-forge metis=5.1.0 -q -y;
          cd $TACS_DIR;
          cp Makefile.in.info Makefile.in;
          make ${{ matrix.OPTIONAL }} TACS_DIR=$TACS_DIR METIS_INCLUDE=-I${CONDA_PREFIX}/include/ METIS_LIB="-L${CONDA_PREFIX}/lib/ -lmetis";
          cd $TACS_DIR;
          make ${{ matrix.INTERFACE }}; 

      - name: Install FUNtoFEM
        run: |
          echo "=============================================================";
          echo "Install FUNtoFEM";
          echo "=============================================================";
          export F2F_DIR=${GITHUB_WORKSPACE};
          echo "F2F_DIR=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
          cd $F2F_DIR;
          cp Makefile.in.info Makefile.in;
          make ${{ matrix.OPTIONAL }} F2F_DIR=$F2F_DIR METIS_INCLUDE=-I${CONDA_PREFIX}/include/ METIS_LIB="-L${CONDA_PREFIX}/lib/ -lmetis";
          cd $F2F_DIR;
          make ${{ matrix.INTERFACE }};

      - name: Run tests
        run: |
          echo "=============================================================";
          echo "Running all tests";
          echo "=============================================================";
          cd ${GITHUB_WORKSPACE}
          testflo ${GITHUB_WORKSPACE}/tests/; 
          
